#!/usr/bin/env bash
FORCE=0
PUSH=1
# echo "$@" # for debug
for arg
do
    case "$arg" in
        --force)
            FORCE=1
            ;;
        --no-push)
            PUSH=0
            ;;
    esac
done

IMAGE="dralec/${PWD##*/}"
echo "Building image: ${IMAGE}"
if [[ ${FORCE} == 0 ]]
then
  docker build -t "${IMAGE}" .
else
  docker build --no-cache -t "${IMAGE}" .
fi

if [ $? -eq 0 ]
then
  if [[ ${PUSH} == 1 ]]
  then
    echo "Pushing"
    docker push "${IMAGE}"
  fi
else
  echo "Could not build an image" >&2
  notify-send "🐳 Docker" "'${IMAGE}' build ERROR" -u critical
  exit 1
fi

notify-send "🐳 Docker" "'${IMAGE}' built successfully."
