#!/usr/bin/env bash
WORKDIR="${WORKDIR:-/usr/src/app}";

YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

pip-install () {
  printf "${YELLOW}Processing:${NC} ${1}\n"
  if [[ -e "${1}" ]]
  then
    pip install -r "${1}" --user
  else
    printf "${RED}Not found:${NC} ${1}\n"
  fi
}

pip-install "$WORKDIR/requirements.txt"
pip-install "$WORKDIR/requirements-dev.txt"
